import { Repository } from "./RepositoryCard";

export const mockRepositories: Repository[] = [
  {
    id: "1",
    slug: "nextjs-saas-starter",
    name: "Next.js SaaS Starter Kit",
    shortDescription: "A complete SaaS starter template with authentication, billing, and dashboard. Production-ready with Stripe integration.",
    techStack: ["Next.js", "TypeScript", "Tailwind", "Prisma", "Stripe"],
    author: {
      name: "Alex Chen",
      username: "alexchen",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    },
    previewImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=450&fit=crop",
    stars: 2847,
    forks: 423,
    downloads: 8921,
    demoUrl: "https://demo.example.com",
    category: "SaaS",
    featured: true,
  },
  {
    id: "2",
    slug: "react-dashboard-pro",
    name: "React Dashboard Pro",
    shortDescription: "Modern admin dashboard with 50+ components, dark mode, and real-time analytics charts.",
    techStack: ["React", "TypeScript", "Recharts", "Tailwind"],
    author: {
      name: "Sarah Miller",
      username: "sarahmiller",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    },
    previewImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop",
    stars: 1923,
    forks: 287,
    downloads: 5432,
    demoUrl: "https://demo.example.com",
    category: "Dashboard",
    featured: true,
  },
  {
    id: "3",
    slug: "ecommerce-platform",
    name: "E-Commerce Platform",
    shortDescription: "Full-featured e-commerce solution with cart, checkout, and inventory management.",
    techStack: ["Next.js", "MongoDB", "Stripe", "Tailwind", "Redux"],
    author: {
      name: "James Wilson",
      username: "jameswilson",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    },
    previewImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=450&fit=crop",
    stars: 3421,
    forks: 567,
    downloads: 12043,
    demoUrl: "https://demo.example.com",
    category: "E-Commerce",
  },
  {
    id: "4",
    slug: "ai-chatbot-template",
    name: "AI Chatbot Template",
    shortDescription: "Production-ready AI chatbot with OpenAI integration, conversation history, and streaming responses.",
    techStack: ["React", "Node.js", "OpenAI", "Socket.io"],
    author: {
      name: "Emma Davis",
      username: "emmadavis",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    },
    previewImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=450&fit=crop",
    stars: 4562,
    forks: 892,
    downloads: 15678,
    category: "AI/ML",
    featured: true,
  },
  {
    id: "5",
    slug: "portfolio-starter",
    name: "Developer Portfolio Starter",
    shortDescription: "Beautiful portfolio template for developers with blog, projects showcase, and contact form.",
    techStack: ["Astro", "React", "Tailwind", "MDX"],
    author: {
      name: "Michael Brown",
      username: "michaelbrown",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    },
    previewImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop",
    stars: 982,
    forks: 156,
    downloads: 3210,
    demoUrl: "https://demo.example.com",
    category: "Portfolio",
  },
  {
    id: "6",
    slug: "mobile-app-ui-kit",
    name: "Mobile App UI Kit",
    shortDescription: "Cross-platform UI components for React Native with 100+ customizable screens.",
    techStack: ["React Native", "TypeScript", "Expo", "NativeWind"],
    author: {
      name: "Lisa Anderson",
      username: "lisaanderson",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face",
    },
    previewImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=450&fit=crop",
    stars: 1567,
    forks: 234,
    downloads: 6789,
    category: "Mobile",
  },
];

export const categories = [
  "All",
  "SaaS",
  "Dashboard",
  "E-Commerce",
  "AI/ML",
  "Portfolio",
  "Mobile",
  "API",
  "CMS",
];

export const techStackFilters = [
  "React",
  "Next.js",
  "Vue",
  "Angular",
  "TypeScript",
  "Node.js",
  "Python",
  "Tailwind",
  "MongoDB",
  "PostgreSQL",
];
